apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loan-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: loan
  namespaceSelector:
    matchNames:
      - vasta
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s