version: "3.8"

services:
  # =========================
  # MySQL
  # =========================
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vasta_system
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - vasta-network

  # =========================
  # Redis
  # =========================
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - vasta-network

  # =========================
  # Zookeeper
  # =========================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc localhost 2181 | grep imok"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - vasta-network

  # =========================
  # Kafka
  # =========================
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      zookeeper:
        condition: service_healthy
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - vasta-network

  # =========================
  # Eureka Server (Distroless)
  # =========================
  eureka-server:
    image: akta2910/vasta-eureka:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - vasta-network


  # =========================
  # Auth Service (Distroless)
  # =========================
  auth-service:
    image: akta2910/vasta-auth:latest
    container_name: auth-service
    ports:
      - "8081:8081"
    volumes:
      - ./secrets:/etc/secrets:ro
      - ./config:/app/config:ro
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - vasta-network


  # =========================
  # User Service (Distroless)
  # =========================
  user-service:
    image: akta2910/vasta-user:latest
    container_name: user-service
    volumes:
      - ./config:/app/config:ro
    ports:
      - "8082:8082"
    depends_on:
      auth-service:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - vasta-network

  # =========================
  # Account Service (Distroless)
  # =========================
  account-service:
    image: akta2910/vasta-account:latest
    container_name: account-service
    volumes:
      - ./config:/app/config:ro
    ports:
      - "8083:8083"
    depends_on:
      auth-service:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - vasta-network

  # =========================
  # Transaction Service (Distroless)
  # =========================
  transaction-service:
    image: akta2910/vasta-transaction:latest
    container_name: transaction-service
    volumes:
      - ./config:/app/config:ro
    ports:
      - "8084:8084"
    depends_on:
      kafka:
        condition: service_started
      auth-service:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - vasta-network

  # =========================
  # Loan Service (Distroless)
  # =========================
  loan-service:
    image: akta2910/vasta-loan:latest
    container_name: loan-service
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/vasta_loans?createDatabaseIfNotExist=true
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    volumes:
      - ./config:/app/config:ro
    ports:
      - "8086:8086"
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - vasta-network


  # =========================
  # kyc Service (Distroless)
  # =========================
  kyc-service:
    image: akta2910/vasta-kyc:latest
    container_name: kyc-service
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - ./config:/app/config:ro
    ports:
      - "8087:8087"
    depends_on:
      kafka:
        condition: service_started
      auth-service:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - vasta-network

  # =========================
  # admin Service (Distroless)
  # =========================
  admin-service:
    image: akta2910/vasta-admin:latest
    container_name: admin-server
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - ./config:/app/config:ro
    ports:
      - "8088:8088"
    depends_on:
      kafka:
        condition: service_started
      auth-service:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - vasta-network

#   =========================
#   payment Service (Distroless)
#   =========================
  payment-service:
    image: akta2910/vasta-payment:latest
    container_name: payment-server
    #    environment:
    #      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - ./config:/app/config:ro
    ports:
      - "8089:8089"
    depends_on:
      kafka:
        condition: service_started
      auth-service:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - vasta-network
  # =========================
  # Notification Service (Distroless)
  # =========================
  notification-service:
    image: akta2910/vasta-notify:latest
    container_name: notification-service
    environment:
      EMAIL_PASSWORD: wtliwgoqkzrgrlcg
    volumes:
      - ./config:/app/config:ro
    ports:
      - "8085:8085"
    depends_on:
      kafka:
        condition: service_started
      auth-service:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - vasta-network

# =========================
# Volumes
# =========================
volumes:
  mysql_data:
  kafka_data:

# =========================
# Network
# =========================
networks:
  vasta-network:
    driver: bridge
