apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vasta-ingress
  namespace: vasta-bank
spec:
  rules:
    - host: vastabank.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80