apiVersion: v1
kind: Secret
metadata:
  name: vasta-secret
  namespace: vasta-bank
type: Opaque
stringData:
  MYSQL_USERNAME: root
  MYSQL_PASSWORD: Abrar@1234
  private.key: |
   -----BEGIN RSA PRIVATE KEY-----
    0jgXQdxG3TspeC8ceBxqQn+fWheiK/pXkBfjSZ8HiIWlY5r2Hr381gKeGyDuma+l7IoNMjC6lfEY
    91olcgw1UXmvhftSN39LWYZ8oMgu7m4vwaVzr9pgpGUFx84TRyQKx4HhlpxOiVGbf8LY9cgRNk2H
    0HNij7X6m4Z2vW3YOsmHW+O5og6PJJ5E/nyTMm9t8ZfwOnRDQPlnXph2ZmvU4V6mhhCiv+VwjdZU
    Ry1idjwTU/NfVGJ39Cz7jeIpLIA3bua4PmoIpKrjyUDmJ7osqMelZEfjeQR137HXUyR1ppXohUch
    jNWPjg8ZoL/I6fT0BD9or1Mk91FAroEFt+8NyQEAAUe7ghwkKT42gOkU0lceAxhb6ilY5SqyiwyN
    Si6GCJEKYaxCZXeKBuuUCxVgwGpK6Ih1dxlITXL6yTUmWp63Eb6SklVas+xiEHklDgPjKziK+trO
    NVKtZsrR+g37ANMGtnLrm+nDvnzXDwOinlwH/++StyRnKxu00iYd1QjAocc0/Onoaz3HeNK0V6nf
    nxy/ytWMTxKIh1+uUwhy7ZBE5Q0LD8iGqC8yP+vQZTkS4akYQoqx7qKu1LEUC12+XACfluh4PV9b
    /O08PUqfb0M5j7mquP34l1i/Wo7ZXJK4NDS1viukAgYFNxa+DisTy98mvK4kg/GAfuJutTdXUzT7
    9B0=
    -----END RSA PRIVATE KEY-----
    

  public.key: |
    -----BEGIN PUBLIC KEY-----
    0jgXQdxG3TspeC8ceBxqQn+fWheiK/pXkBfjSZ8HiIWlY5r2Hr381gKeGyDuma+l7IoNMjC6lfEY
    91olcgw1UXmvhftSN39LWYZ8oMgu7m4vwaVzr9pgpGUFx84TRyQKx4HhlpxOiVGbf8LY9cgRNk2H
    0HNij7X6m4Z2vW3YOsmHW+O5og6PJJ5E/nyTMm9t8ZfwOnRDQPlnXph2ZmvU4V6mhhCiv+VwjdZU
    Ry1idjwTU/NfVGJ39Cz7jeIpLIA3bua4PmoIpKrjyUDmJ7osqMelZEfjeQR137HXUyR1ppXohUch
    jNWPjg8ZoL/I6fT0BD9or1Mk91FAroEFt+8NyQEAAQ==
    -----END PUBLIC KEY-----
