apiVersion: v1
kind: Secret
metadata:
  name: vasta-secret
  namespace: vasta-bank
type: Opaque
stringData:
  MYSQL_USERNAME: root
  MYSQL_PASSWORD: root
  private.key: |
  
    

  public.key: |
  
    

  EMAIL_PASSWORD:
  RAZORPAY_KEY:
  RAZORPAY_SECRET: