apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: vasta
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: akta2910/vasta-admin:latest
          envFrom:
            - configMapRef:
                name: vasta-config
            - secretRef:
                name: vasta-secret
          ports:
            - containerPort: 8088
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: vasta
spec:
  selector:
    app: admin
  ports:
    - port: 8088
      targetPort: 8088