apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyc
  namespace: vasta
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kyc
  template:
    metadata:
      labels:
        app: kyc
    spec:
      containers:
        - name: kyc
          image: akta2910/vasta-kyc:latest
          envFrom:
            - configMapRef:
                name: vasta-config
            - secretRef:
                name: vasta-secret
          ports:
            - containerPort: 8087
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: kyc
  namespace: vasta
spec:
  selector:
    app: kyc
  ports:
    - port: 8087
      targetPort: 8087